version: '2'

services:

  vault:
    image: enclaive/hashicorp-vault-sgx:k8s
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
      - "/dev/sgx/enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    volumes:
      - type: volume
        target: /data
    ports:
      - "8200:8200"
    environment:
      - ENCLAIVE_DEPLOYMENT=${ENCLAIVE_DEPLOYMENT}